export const FONT_PAIRINGS = [
  {
    id: 'editorial-power',
    name: 'Editorial Power',
    vibe: 'Magazine · Bold · High-Impact',
    use: 'Perfect for editorial brands, luxury campaigns, print magazines',
    display: { name: 'Playfair Display', family: "'Playfair Display', Georgia, serif", weight: 700, style: 'italic', category: 'Serif' },
    body:    { name: 'Raleway',          family: "'Raleway', sans-serif",              weight: 400,                  category: 'Sans-Serif' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,700&family=Raleway:wght@400;500&display=swap',
    specimen: { heading: 'The Art of Bold Design', sub: 'Volume XII · Spring Edition', body: 'Great design speaks before it is read. Typography is not just type — it is voice, rhythm, and personality distilled into letterforms.' },
    tags: ['Editorial', 'Luxury', 'Print'],
  },
  {
    id: 'modernist-tech',
    name: 'Modernist Tech',
    vibe: 'Clean · Systematic · Digital',
    use: 'Ideal for SaaS products, tech startups, developer tools',
    display: { name: 'Space Grotesk', family: "'Space Grotesk', sans-serif", weight: 700, category: 'Sans-Serif' },
    body:    { name: 'Inter',          family: "'Inter', sans-serif",          weight: 400, category: 'Sans-Serif' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@700&family=Inter:wght@400;500&display=swap',
    specimen: { heading: 'Build Without Limits', sub: 'Platform · API · Scale', body: 'Systems thinking meets visual clarity. Every pixel serves a purpose. Every typeface choice communicates intent and builds trust with precision.' },
    tags: ['SaaS', 'Tech', 'Digital'],
  },
  {
    id: 'artisan-warmth',
    name: 'Artisan Warmth',
    vibe: 'Craft · Human · Inviting',
    use: 'Great for food brands, independent studios, handmade goods',
    display: { name: 'Cormorant Garamond', family: "'Cormorant Garamond', serif", weight: 600, style: 'italic', category: 'Serif' },
    body:    { name: 'Jost',               family: "'Jost', sans-serif",             weight: 400,                 category: 'Sans-Serif' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,600&family=Jost:wght@400;500&display=swap',
    specimen: { heading: 'Crafted With Intention', sub: 'Est. 2019 · Small Batch', body: 'Handcrafted is not just a process — it is a philosophy. Slow, considered, and made for those who believe the details are worth it.' },
    tags: ['Food', 'Artisan', 'Lifestyle'],
  },
  {
    id: 'brutalist-energy',
    name: 'Brutalist Energy',
    vibe: 'Raw · Loud · Unapologetic',
    use: 'Perfect for streetwear, music, youth culture, experimental brands',
    display: { name: 'Bebas Neue',   family: "'Bebas Neue', sans-serif", weight: 400, category: 'Display' },
    body:    { name: 'DM Mono',      family: "'DM Mono', monospace",     weight: 400, category: 'Monospace' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:wght@400;500&display=swap',
    specimen: { heading: 'BREAK THE RULES', sub: 'DROP 003 / LIMITED EDITION', body: 'Function over form. Truth over beauty. We reject the polished surface and embrace what is real, rough, and completely unafraid.' },
    tags: ['Streetwear', 'Music', 'Culture'],
  },
  {
    id: 'refined-minimal',
    name: 'Refined Minimal',
    vibe: 'Quiet · Elegant · Timeless',
    use: 'Excellent for architecture, luxury goods, premium portfolios',
    display: { name: 'Libre Baskerville', family: "'Libre Baskerville', serif", weight: 700, category: 'Serif' },
    body:    { name: 'Lato',              family: "'Lato', sans-serif",           weight: 300, category: 'Sans-Serif' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Lato:wght@300;400&display=swap',
    specimen: { heading: 'Less, But Better', sub: 'Architecture · Space · Form', body: 'Restraint is a discipline. When everything unnecessary is removed, what remains speaks with absolute authority. The silence between words carries meaning.' },
    tags: ['Architecture', 'Luxury', 'Portfolio'],
  },
  {
    id: 'geometric-future',
    name: 'Geometric Future',
    vibe: 'Bold · Futuristic · Structured',
    use: 'Strong for fashion, motion design, visual identities',
    display: { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif", weight: 700, category: 'Sans-Serif' },
    body:    { name: 'Nunito',       family: "'Nunito', sans-serif",        weight: 400, category: 'Sans-Serif' },
    googleUrl: 'https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@700&family=Nunito:wght@400;500&display=swap',
    specimen: { heading: 'Form Follows Vision', sub: 'Collection No.7 · 2025', body: 'Geometry is the language of structure. Bold letterforms command space and declare intention. This is design that knows exactly what it wants to say.' },
    tags: ['Fashion', 'Identity', 'Motion'],
  },
];

export const FONT_CATEGORIES = ['All', 'Editorial', 'Tech', 'Luxury', 'Artisan', 'Bold'];

export const TYPE_SCALE = [
  { name: 'Display', rem: '3.5rem', use: 'Hero headlines, poster type' },
  { name: 'H1',      rem: '2.5rem', use: 'Page titles, section heroes' },
  { name: 'H2',      rem: '2rem',   use: 'Section headings' },
  { name: 'H3',      rem: '1.5rem', use: 'Sub-sections, card titles' },
  { name: 'H4',      rem: '1.25rem',use: 'Labels, sidebar headers' },
  { name: 'Body',    rem: '1rem',   use: 'Body copy, paragraphs' },
  { name: 'Small',   rem: '0.875rem',use: 'Captions, metadata' },
  { name: 'Micro',   rem: '0.75rem', use: 'Tags, timestamps, badges' },
];

export const TRENDING_FONTS = [
  { name: 'Instrument Serif',  trend: '↑ Hot', vibe: 'Refined editorial with personality' },
  { name: 'General Sans',      trend: '↑ Rising', vibe: 'Geometric sans for modern brands' },
  { name: 'Sentient',          trend: '↑ New', vibe: 'Contemporary serif with warmth' },
  { name: 'Cabinet Grotesk',   trend: '→ Steady', vibe: 'Versatile grotesque, wide weight range' },
  { name: 'Clash Display',     trend: '↑ Popular', vibe: 'Bold display for visual impact' },
];
